# Generated by Django 2.2.5 on 2019-11-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('views', models.IntegerField(null=True)),
                ('image', models.ImageField(upload_to='productImages/')),
                ('dateUploaded', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
