# Generated by Django 2.2.5 on 2019-11-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsHome', '0002_auto_20191108_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(height_field='400', upload_to='productImages/', width_field='400'),
        ),
    ]
