# Generated by Django 2.2.5 on 2019-11-09 10:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productsHome', '0004_auto_20191108_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=None)),
                ('Y', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=None)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='actualViews',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='dateTimeUploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
