# Generated by Django 2.2.5 on 2019-11-09 10:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsHome', '0006_auto_20191109_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='views',
            name='X',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=None),
        ),
        migrations.AlterField(
            model_name='views',
            name='Y',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=None),
        ),
    ]
