# Generated by Django 2.2.5 on 2019-11-09 11:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsHome', '0007_auto_20191109_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='views',
            name='Y',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=2), size=None),
        ),
    ]
