# Generated by Django 2.2.5 on 2019-11-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsHome', '0008_auto_20191109_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['title']},
        ),
    ]
