# Generated by Django 2.2.5 on 2019-11-09 14:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsHome', '0009_auto_20191109_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='views',
            name='Y',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), size=None),
        ),
    ]
