# Generated by Django 2.2.5 on 2019-11-09 16:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('productsHome', '0010_auto_20191109_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='dateTimeUploaded',
        ),
        migrations.AddField(
            model_name='products',
            name='Daytimestamp',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2019, 11, 9, 16, 29, 29, 95525, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
