# Generated by Django 2.2.5 on 2019-11-09 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productsHome', '0011_auto_20191109_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='views',
            name='Viewtimestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
