# Generated by Django 2.2.5 on 2019-11-09 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsHome', '0012_views_viewtimestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='views',
            name='Viewtimestamp',
        ),
    ]
