# Generated by Django 2.2.5 on 2019-11-09 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsHome', '0013_remove_views_viewtimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='views',
            name='Viewtimestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 11, 9, 17, 23, 52, 737507)),
            preserve_default=False,
        ),
    ]
