# Generated by Django 2.2.5 on 2019-11-09 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsHome', '0015_remove_views_viewtimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='views',
            name='Viewtimestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 11, 9, 18, 24, 28, 252013)),
            preserve_default=False,
        ),
    ]
