# Generated by Django 2.2.5 on 2019-11-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsHome', '0016_views_viewtimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='views',
            field=models.FloatField(null=True),
        ),
    ]
